#!/usr/bin/env python
# -*- Python -*-
#
# ----------------------------------------------------------------------
#
# Brad T. Aagaard, U.S. Geological Survey
#
# This code was developed as part of the Computational Infrastructure
# for Geodynamics (http://geodynamics.org).
#
# Copyright (c) 2010-2016 University of California, Davis
#
# See COPYING for license information.
#
# ----------------------------------------------------------------------
#

# Start web server for browse-based GUI application for viewing PyLith
# parameters.

if __name__ == "__main__":

    description = "Starts web server for running browser-based GUI for viewing PyLith parameters."
    addInfo = "IMPORTANT: You must run this script from the directory with the index.html file. " \
              "After starting server, point your browser to 127.0.0.1:9000 (or user-specified port)."

    import argparse
    parser = argparse.ArgumentParser(description=description, epilog=addInfo)
    parser.add_argument("--port", action="store", type=int, dest="port", help="Port for web server (default: 9000).", default=9000)
    args = parser.parse_args()

    import SimpleHTTPServer
    import SocketServer

    address = ('127.0.0.1', args.port)
    handler = SimpleHTTPServer.SimpleHTTPRequestHandler
    httpd = SocketServer.TCPServer(address, handler)
    print "Point your browser to %s:%s" % address

    httpd.serve_forever()


# End of file
